services:
  core-ai:
    build:
      dockerfile: ./apps/core-ai/Dockerfile
    container_name: core-ai
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env

  discord_bot:
    build:
      dockerfile: ./apps/discord/Dockerfile
    container_name: discord_bot
    restart: always
