services:
  core_ai:
    build:
      dockerfile: ./apps/core-ai/Dockerfile
    container_name: core_ai
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  mott_discord_bot:
    build:
      dockerfile: ./apps/discord/Dockerfile
    container_name: mott_discord_bot
    restart: always
