# install
FROM oven/bun:1 AS install
WORKDIR /app/
RUN \
    --mount=type=bind,target=package.json,source=package.json \
    --mount=type=bind,target=apps/core-ai/package.json,source=apps/core-ai/package.json \
    --mount=type=bind,target=packages/db/package.json,source=packages/db/package.json \
    --mount=type=bind,target=packages/emails/package.json,source=packages/emails/package.json \
    --mount=type=bind,target=packages/error/package.json,source=packages/error/package.json \
    --mount=type=bind,target=tooling/eslint/package.json,source=tooling/eslint/package.json \
    --mount=type=bind,target=tooling/prettier/package.json,source=tooling/prettier/package.json \
    --mount=type=bind,target=tooling/typescript/package.json,source=tooling/typescript/package.json \
    --mount=type=bind,target=tooling/tailwind/package.json,source=tooling/tailwind/package.json \
    --mount=type=cache,target=/root/.bun/install/cache,sharing=locked \
    bun install --production --ignore-scripts --frozen-lockfile
